feat: Hunger logo game search button
openfoodfacts/power-user-script pull request #85
Opened 2023-12-30 19:16 UTC by DanieliusAsm

### What
- 

### Screenshot

### Fixes bug(s)
- 

### Part of 
-

2024-01-03 11:19 UTC, CharlesNepote requested changes
Great!
2 little points:
* you should upgrade version to allow people automatically upgrade
* why not always display this link as it does not impact products' card too much contrary to barcode?

2024-01-03 11:21 UTC, CharlesNepote approved these changes

2024-01-03 12:25 UTC, merged

2024-01-08 09:34 UTC, DanieliusAsm commented
@CharlesNepote 

- I didnt know about the version thing since I dont have prior expeirience to User scripts.
- I planned to make this change in the future. I would want to add more buttons so there should be a toggle (maybe not for this hunger game button). Ideally I would want to add buttons: rotate left, rotate right, delete buttons if I could figure out the rotation stuff

2024-01-08 12:46 UTC, CharlesNepote commented
> I didnt know about the version thing since I dont have prior expeirience to User scripts.

Yes we should document development process a little bit.

> I planned to make this change in the future. I would want to add more buttons so there should be a toggle (maybe not for this hunger game button). Ideally I would want to add buttons: rotate left, rotate right, delete buttons if I could figure out the rotation stuff.

Great! Have you seen: https://openfoodfacts.github.io/openfoodfacts-server/api/ref-v2/#get-/cgi/product_image_crop.pl

> The delete button would be seen by everyone not just mods so thats problematic as there is no way of knowing if a user is a mod. It should probably be hidden by default and be toggleable

There is an ongoing bug here that would allow you to test if a user is an admin or not: https://github.com/openfoodfacts/openfoodfacts-server/issues/6758