feat:Rotate image
openfoodfacts/power-user-script pull request #88
Opened 2024-02-01 20:07 UTC by DanieliusAsm

### What
- Rotate images left and right

### Screenshot
![image](https://github.com/openfoodfacts/power-user-script/assets/22033222/2078ee79-1029-4469-adfd-f03d5963a786)

2024-02-01 20:11 UTC, DanieliusAsm commented
Im having some issues:

- From looking at [api docs](https://openfoodfacts.github.io/openfoodfacts-server/api/ref-v2/#get-/cgi/product_image_crop.pl ) I see that id like (front_en) and imageid like '1' is required.
- I want to rotate the currently selected image, I dont know its id.
- I also want to rotate front_lc. I dont know which lc is used.
- I can try rotating front_en by default but that causes problems if you use a different than world.openfoodfacs subdomain like it.openfoodfacts

2024-02-01 20:17 UTC, DanieliusAsm commented
I am having some troubles:

- Rotate image needs id and imageid. I Need to rotate the currently selected image.
- the id might be front_it but I try and rotate front_en

2024-02-06 16:04 UTC, CharlesNepote requested changes
This is really a great job!! I have suggested to change the icons but please do what you prefer.

2024-02-06 16:04 UTC, CharlesNepote commented on OpenFoodFactsPower.user.js
> +            $(this).append('<a class="list_rotate_image_270" alt="Rotate at 270°" title="Rotate at 270°"><span class="material-icons" style="transform: rotate(-90deg);">rotate_left</span></a>');
I feel the icons you're using are hard to read/understand. I suggest these other icons, feel free to adopt or reject it:
```suggestion
            $(this).append('<a class="list_rotate_image_270" alt="Rotate at -90°" title="Rotate at -90°"><span class="material-icons"  style="transform: scaleX(-1);">redo</span></a>');
```

2024-02-06 16:04 UTC, CharlesNepote commented on OpenFoodFactsPower.user.js
> +            $(this).append('<a class="list_rotate_image_180" alt="Rotate at 180°" title="Rotate at 180°"><span class="material-icons">rotate_left</span></a>');
```suggestion
            $(this).append('<a class="list_rotate_image_180" alt="Rotate at 180°" title="Rotate at 180°"><span class="material-icons">rotate_right</span></a>');
```

2024-02-06 16:04 UTC, CharlesNepote commented on OpenFoodFactsPower.user.js
> +            $(this).append('<a class="list_rotate_image_90" alt="Rotate at 90°" title="Rotate at 90°"><span class="material-icons" style="transform: rotate(90deg);">rotate_right</span></a>');
```suggestion
            $(this).append('<a class="list_rotate_image_90" alt="Rotate at 90°" title="Rotate at 90°"><span class="material-icons">redo</span></a>');
```

2024-02-06 16:04 UTC, CharlesNepote commented on OpenFoodFactsPower.user.js
> +            $(this).append('<a class="list_rotate_image_90" alt="Rotate at 90°" title="Rotate at 90°"><span class="material-icons" style="transform: rotate(90deg);">rotate_right</span></a>');
Here is the result:
![image](https://github.com/openfoodfacts/power-user-script/assets/562352/c03ae6cd-caa7-4c7c-879a-36a5b17ca9f3)

2024-02-06 16:47 UTC, DanieliusAsm commented
@CharlesNepote your icons should be easier to understand since the ones I am using show a 180 degree turn. Also I probably could reduce it to 2 rotate icons. 

When you click to rotate at first it sends request to get images, from there I can get the current rotation and end up using 2 instead of 3 buttons. Just need to try it out and see if I can get it working.

2024-02-07 07:05 UTC, merged